import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Y-Combinator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  newsFeed
}: Readonly<{
  children: React.ReactNode,
  newsFeed: React.ReactNode
}>) {
  return (
    <>
        <h1 className="text-3xl">I'm a root layout, but does not appear on dashboard route group.</h1>
        {children}
        {newsFeed}
    </>
  );
}
